enum Constants {
    projectName="Fanaka",
    course="Computer Science",
    footerMessage="Made with ❤ by bkyole",
    dashboard="Dashboard",
    path="/dashboard",
    yearOne="First Year",
    yearTwo = "Second Year",
    yearThree = "Third Year",
    yearFour = "Fourth Year",
    valueOne="/dashboard/firstyear",
    valueTwo ="/dashboard/secondyear",
    valueThree = "/dashboard/thirdyear",
    valueFour = "/dashboard/fourthyear",
    SemesterOnePointOne = "1.1",
    SemesterOnePointTwo = "1.2",
    SemesterTwoPointOne = "2.1",
    SemesterTwoPointTwo = "2.2",
    SemesterThreePointOne = "3.1",
    SemesterThreePointTwo = "3.2",
    SemesterFourPointOne = "4.1",
    SemesterFourPointTwo = "4.2",
}

export default Constants;