import Constants from '../InterfacesEnumsTypes/Enums/Enums';

export const PROJECTNAME : Constants = Constants.projectName;
export const COURSE :Constants = Constants.course;
export const FOOTER_MESSAGE : Constants = Constants.footerMessage;
export const DASHBOARD:Constants = Constants.dashboard;
export const PATH:Constants = Constants.path;
export const YEAR_ONE:Constants = Constants.yearOne;
export const YEAR_TWO: Constants = Constants.yearTwo;
export const YEAR_THREE: Constants = Constants.yearThree;
export const YEAR_FOUR: Constants = Constants.yearFour;
export const VALUE_ONE:Constants = Constants.valueOne;
export const VALUE_TWO:Constants = Constants.valueTwo;
export const VALUE_THREE: Constants = Constants.valueThree;
export const VALUE_FOUR: Constants = Constants.valueFour;
export const SEMESTER_ONE_POINT_ONE : Constants = Constants.SemesterOnePointOne;
export const SEMESTER_ONE_POINT_TWO : Constants = Constants.SemesterOnePointTwo;
export const SEMESTER_TWO_POINT_ONE : Constants = Constants.SemesterTwoPointOne;
export const SEMESTER_TWO_POINT_TWO : Constants = Constants.SemesterTwoPointTwo;
export const SEMESTER_THREE_POINT_ONE : Constants = Constants.SemesterThreePointOne;
export const SEMESTER_THREE_POINT_TWO : Constants = Constants.SemesterThreePointTwo;
export const SEMESTER_FOUR_POINT_ONE : Constants = Constants.SemesterFourPointOne;
export const SEMESTER_FOUR_POINT_TWO : Constants = Constants.SemesterFourPointTwo;